create table
  public."userDatabase" (
    created_at timestamp with time zone null default now(),
    username text null,
    email character varying null,
    password character varying null,
    "cryptoAddress" text null,
    "seedPhrase" text[] null,
    posts text[] null,
    notifications text[] null,
    tickets text[] null,
    "levelXP" text null,
    nfts text[] null,
    "friendsList" text[] null,
    "artistsFollowed" text[] null,
    "fandomList" text[] null,
    "leaderboardRanks" text null,
    "boughtExperiences" text[] null,
    "upcomingExperiences" text[] null,
    "publishedExperiences" text[] null,
    "storedExperiences" text[] null,
    "pastExperiences" text[] null,
    "recommendedExperiences" text[] null,
    "tradedNFTs" text[] null,
    "groupChats" text[] null,
    "universalLocationData" text null,
    "pastLocationData" text[] null,
    "inGameLocation" text[] null,
    "inventoryInGame" text[] null,
    "questsListsInGame" text[] null,
    "userId" uuid not null default auth.uid (),
    avatar text null,
    constraint userDatabase_pkey primary key ("userId"),
    constraint userDatabase_notifications_key unique (notifications),
    constraint userDatabase_friendsList_key unique ("friendsList"),
    constraint userDatabase_boughtExperiences_key unique ("boughtExperiences"),
    constraint userDatabase_storedExperiences_key unique ("storedExperiences"),
    constraint userDatabase_tradedNFTs_key unique ("tradedNFTs"),
    constraint userDatabase_questsListsInGame_key unique ("questsListsInGame"),
    constraint userDatabase_seedPhrase_key unique ("seedPhrase"),
    constraint userDatabase_tickets_key unique (tickets),
    constraint userDatabase_artistsFollowed_key unique ("artistsFollowed"),
    constraint userDatabase_upcomingExperiences_key unique ("upcomingExperiences"),
    constraint userDatabase_pastExperiences_key unique ("pastExperiences"),
    constraint userDatabase_groupChats_key unique ("groupChats"),
    constraint userDatabase_cryptoAddress_key unique ("cryptoAddress"),
    constraint userDatabase_username_key unique (username),
    constraint userDatabase_leaderboardRanks_key unique ("leaderboardRanks"),
    constraint userDatabase_posts_key unique (posts),
    constraint userDatabase_nfts_key unique (nfts),
    constraint userDatabase_fandomList_key unique ("fandomList"),
    constraint userDatabase_publishedExperiences_key unique ("publishedExperiences"),
    constraint userDatabase_recommendedExperiences_key unique ("recommendedExperiences"),
    constraint userDatabase_inventoryInGame_key unique ("inventoryInGame")
  ) tablespace pg_default;