create table "public"."userDatabase" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text
)
alter table "public"."userDatabase" enable row level security
CREATE UNIQUE INDEX "userDatabase_pkey" ON public."userDatabase" USING btree (id)
alter table "public"."userDatabase" add constraint "userDatabase_pkey" PRIMARY KEY using index "userDatabase_pkey"
grant delete on table "public"."userDatabase" to "anon"
grant insert on table "public"."userDatabase" to "anon"
grant references on table "public"."userDatabase" to "anon"
grant select on table "public"."userDatabase" to "anon"
grant trigger on table "public"."userDatabase" to "anon"
grant truncate on table "public"."userDatabase" to "anon"
grant update on table "public"."userDatabase" to "anon"
grant delete on table "public"."userDatabase" to "authenticated"
grant insert on table "public"."userDatabase" to "authenticated"
grant references on table "public"."userDatabase" to "authenticated"
grant select on table "public"."userDatabase" to "authenticated"
grant trigger on table "public"."userDatabase" to "authenticated"
grant truncate on table "public"."userDatabase" to "authenticated"
grant update on table "public"."userDatabase" to "authenticated"
grant delete on table "public"."userDatabase" to "service_role"
grant insert on table "public"."userDatabase" to "service_role"
grant references on table "public"."userDatabase" to "service_role"
grant select on table "public"."userDatabase" to "service_role"
grant trigger on table "public"."userDatabase" to "service_role"
grant truncate on table "public"."userDatabase" to "service_role"
grant update on table "public"."userDatabase" to "service_role"